import AppKit

/// The Adonis Eclipse theme.
///
/// Ported with `Scripts/import-vscode-theme.swift` from the Adonis theme
/// extension by Saeed Nazari, then carried by the app: colours read live from
/// somebody's VS Code would be missing on every other Mac.
extension SyntaxPalette {
    static let adonisEclipse = SyntaxPalette(
        name: "Adonis Eclipse",
        foreground: NSColor(rgb: 0xCC_CC_CC),
        background: NSColor(rgb: 0x18_1A_1D),
        lineNumber: NSColor(rgb: 0x49_51_62),
        currentLine: NSColor(rgb: 0x24_26_2B),
        indentGuide: NSColor(rgb: 0x22_23_26),
        styles: [
            "attribute": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "boolean": SyntaxStyle(color: NSColor(rgb: 0xEE_96_D7)),
            "character": SyntaxStyle(color: NSColor(rgb: 0xED_CB_66)),
            "comment": SyntaxStyle(color: NSColor(rgb: 0x78_84_94)),
            "conditional": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90)),
            "constant": SyntaxStyle(color: NSColor(rgb: 0x84_AC_FC)),
            "constant.builtin": SyntaxStyle(color: NSColor(rgb: 0xEE_96_D7)),
            "constant.macro": SyntaxStyle(color: NSColor(rgb: 0x33_C8_9F)),
            "constructor": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "error": SyntaxStyle(color: NSColor(rgb: 0xFA_67_80)),
            "exception": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90)),
            "field": SyntaxStyle(color: NSColor(rgb: 0xB5_C9_ED)),
            "float": SyntaxStyle(color: NSColor(rgb: 0xEE_96_D7)),
            "function": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "function.call": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "function.macro": SyntaxStyle(color: NSColor(rgb: 0x33_C8_9F)),
            "function.method": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "include": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90)),
            "keyword": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "keyword.function": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "keyword.operator": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "keyword.return": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90)),
            "label": SyntaxStyle(color: NSColor(rgb: 0xCC_CC_CC)),
            "method": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "module": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "namespace": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "number": SyntaxStyle(color: NSColor(rgb: 0xEE_96_D7)),
            "operator": SyntaxStyle(color: NSColor(rgb: 0x9B_BA_D4)),
            "parameter": SyntaxStyle(color: NSColor(rgb: 0xF3_A5_6A)),
            "property": SyntaxStyle(color: NSColor(rgb: 0xB5_C9_ED)),
            "punctuation": SyntaxStyle(color: NSColor(rgb: 0xB0_B0_B0)),
            "punctuation.bracket": SyntaxStyle(color: NSColor(rgb: 0xB0_B0_B0)),
            "punctuation.delimiter": SyntaxStyle(color: NSColor(rgb: 0xB0_B0_B0)),
            "punctuation.special": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "repeat": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90)),
            "storageclass": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "string": SyntaxStyle(color: NSColor(rgb: 0xED_CB_66)),
            "string.escape": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "string.import": SyntaxStyle(color: NSColor(rgb: 0xED_CB_66)),
            "string.regex": SyntaxStyle(color: NSColor(rgb: 0xF3_A5_6A)),
            "string.special": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74)),
            "tag": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "tag.attribute": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "tag.delimiter": SyntaxStyle(color: NSColor(rgb: 0x95_A4_B7)),
            "text.emphasis": SyntaxStyle(color: NSColor(rgb: 0xF3_A5_6A), italic: true),
            "text.literal": SyntaxStyle(color: NSColor(rgb: 0xED_CB_66)),
            "text.strong": SyntaxStyle(color: NSColor(rgb: 0xFF_7A_90), bold: true),
            "text.title": SyntaxStyle(color: NSColor(rgb: 0x9D_D2_74), bold: true),
            "text.uri": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "type": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "type.builtin": SyntaxStyle(color: NSColor(rgb: 0x85_DA_FB)),
            "type.qualifier": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "variable": SyntaxStyle(color: NSColor(rgb: 0xCC_CC_CC)),
            "variable.builtin": SyntaxStyle(color: NSColor(rgb: 0xBB_9C_F7)),
            "variable.member": SyntaxStyle(color: NSColor(rgb: 0xB5_C9_ED)),
            "variable.parameter": SyntaxStyle(color: NSColor(rgb: 0xF3_A5_6A))
        ]
    )
}
